[toolchain]
anchor_version = "0.30.1"
solana_version = "1.18.18"

[features]
resolution = true
skip-lint = false

[programs.devnet]
nft_game_agent_program = "ErQd82jnp2fgvj6h357Nj6gwpcyiNjFENP6cwQ9quaAW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/new_program_keypair.json"

[scripts]
test = "npm run ts-mocha -p ./tsconfig.json -t 2000000 tests/**/*.ts"

[test]
startup_wait = 30000
shutdown_wait = 5000
upgradeable = true
